DATASET: 
  ROOT: "/home/hy/ssd1/tomchen/loveu2023/dataset/assistq_test2023"
  SPLIT: "train"
  LABEL: "train_with_score.json"
MODEL: 
  VISION: "blip"
  TEXT: "blip" # huggingface
INPUT: 
  FPS: 1
  SIZE: [384, 384]
FOR:
  VIDEO: False
  SCRIPT: False
  QA: False
  PARA: False
  GLOBAL: False
  LOCAL: False
  HAND: False
QA:
  NUM_MASKS: -1 # best performance